### ISSUE TITLE
Work with any form

### ISSUE THREAD

**Issue by svipic** [apratt86/clickup-task-forms-free#1]
Hi, 
First its really cool to see as clickup progress and we have some kind of Easy integration in wordpress.
But as we know, Many wordpress websites uses different type of forms.
For example Elementor Pro Form

Instead creating another contact form generator with shortcode, why not create it as general integration with api that will work with any form?

Do we really need another contact form plugin? Not really. 
For example, Elementor is the most popular page builder now, and there contact form at most answers for most website needs. it also has integration from webhook to api's like MailerLite, GetResponse, ActiveCampaign and etc.
Its not has to be different. In most cases its unnececery to ask website owner to change there forms on website for this.

There need to be another approuch to it.

Hope it can be changed
Thanks

-- | --

IT

**Comment by apratt86** [comment]
That's a bit more of a task than what it would seem. There are several required fields that are necessary in order to submit a task to ClickUp, which you would also have to map to the correct destination. Having this function work independently takes out the guess work for the users and requires less set up. Plus, what you're suggesting would require interfacing with several form generators/plugins to alter their form submissions to run through this plugin's callback.
